Resources: # リソースセクション
  CFVPC: # VPCリソース
    Type: AWS::EC2::VPC # リソースタイプはVPC
    Properties: # プロパティセクション
      CidrBlock: 10.0.0.0/20 # VPCのCIDRブロック
      Tags: # タグセクション
        - Key: Name # タグのキー
          Value: CFVPC # タグの値

  CFSubnet: # サブネットリソース
    Type: AWS::EC2::Subnet # リソースタイプはサブネット
    Properties: # プロパティセクション
      VpcId: !Ref CFVPC # VPCリソースへの参照
      CidrBlock: 10.0.0.0/24 # サブネットのCIDRブロック
      Tags: # タグセクション
        - Key: Name # タグのキー
          Value: CFSubnet # タグの値

  CFSecurityGroup: # セキュリティグループリソース
    Type: AWS::EC2::SecurityGroup # リソースタイプはセキュリティグループ
    Properties: # プロパティセクション
      GroupDescription: Allow SSH access # セキュリティグループの説明
      VpcId: !Ref CFVPC # VPCリソースへの参照
      SecurityGroupIngress: # インバウンドルールセクション
        - IpProtocol: tcp # プロトコルはTCP
          FromPort: 22 # 開始ポート
          ToPort: 22 # 終了ポート
          CidrIp: 0.0.0.0/0 # 許可するIP範囲

  CFInstance: # EC2インスタンスリソース
    Type: AWS::EC2::Instance # リソースタイプはEC2インスタンス
    Properties: # プロパティセクション
      InstanceType: t2.micro # インスタンスタイプ
      ImageId: ami-05576a079321f21f8 # AMI ID
      SubnetId: !Ref CFSubnet # サブネットリソースへの参照
      SecurityGroupIds: # セキュリティグループIDセクション
        - !Ref CFSecurityGroup # セキュリティグループリソースへの参照
      KeyName: vockey # キーペアの名前
      BlockDeviceMappings: # ブロックデバイスマッピングセクション
        - DeviceName: /dev/xvda # デバイス名
          Ebs: # EBSセクション
            VolumeSize: 10 # ボリュームサイズ
            VolumeType: gp2 # ボリュームタイプ
      Tags: # タグセクション
        - Key: Name # タグのキー
          Value: CFInstance # タグの値
