AWSTemplateFormatVersion: '2010-09-09' # CloudFormationテンプレートのバージョン
Description: CloudFormationテンプレートでVPCとパブリックサブネットを作成する # テンプレートの説明

Resources:
  CFVPC:
    Type: 'AWS::EC2::VPC' # VPCのリソースタイプ
    Properties:
      CidrBlock: '10.0.0.0/20' # VPCのCIDRブロック
      EnableDnsSupport: true # DNSサポートを有効にする
      EnableDnsHostnames: true # DNSホスト名を有効にする
      Tags:
        - Key: Name
          Value: CFVPC # VPCのタグ

  PublicSubnet:
    Type: 'AWS::EC2::Subnet' # サブネットのリソースタイプ
    Properties:
      VpcId: !Ref CFVPC # VPCへの参照
      CidrBlock: '10.0.1.0/24' # サブネットのCIDRブロック
      MapPublicIpOnLaunch: true # 起動時にパブリックIPを割り当てる
      AvailabilityZone: !Select [ 0, !GetAZs '' ] # 最初のアベイラビリティゾーンを選択
      Tags:
        - Key: Name
          Value: PublicSubnet # サブネットのタグ

  InternetGateway:
    Type: 'AWS::EC2::InternetGateway' # インターネットゲートウェイのリソースタイプ
    Properties:
      Tags:
        - Key: Name
          Value: MyInternetGateway # インターネットゲートウェイのタグ

  AttachGateway:
    Type: 'AWS::EC2::VPCGatewayAttachment' # VPCゲートウェイアタッチメントのリソースタイプ
    Properties:
      VpcId: !Ref CFVPC # VPCへの参照
      InternetGatewayId: !Ref InternetGateway # インターネットゲートウェイへの参照

  PublicRouteTable:
    Type: 'AWS::EC2::RouteTable' # ルートテーブルのリソースタイプ
    Properties:
      VpcId: !Ref CFVPC # VPCへの参照
      Tags:
        - Key: Name
          Value: PublicRouteTable # ルートテーブルのタグ

  PublicRoute:
    Type: 'AWS::EC2::Route' # ルートのリソースタイプ
    Properties:
      RouteTableId: !Ref PublicRouteTable # ルートテーブルへの参照
      DestinationCidrBlock: '0.0.0.0/0' # デスティネーションCIDRブロック
      GatewayId: !Ref InternetGateway # インターネットゲートウェイへの参照

  SubnetRouteTableAssociation:
    Type: 'AWS::EC2::SubnetRouteTableAssociation' # サブネットルートテーブルアソシエーションのリソースタイプ
    Properties:
      SubnetId: !Ref PublicSubnet # サブネットへの参照
      RouteTableId: !Ref PublicRouteTable # ルートテーブルへの参照

  CFSecurityGroup: # セキュリティグループリソース
    Type: AWS::EC2::SecurityGroup # リソースタイプはセキュリティグループ
    Properties: # プロパティセクション
      GroupDescription: Allow SSH access # セキュリティグループの説明
      VpcId: !Ref CFVPC # VPCリソースへの参照
      SecurityGroupIngress: # インバウンドルールセクション
        - IpProtocol: tcp # プロトコルはTCP
          FromPort: 22 # 開始ポート
          ToPort: 22 # 終了ポート
          CidrIp: 0.0.0.0/0 # 許可するIP範囲

  CFInstance: # EC2インスタンスリソース
    Type: AWS::EC2::Instance # リソースタイプはEC2インスタンス
    Properties: # プロパティセクション
      InstanceType: t2.micro # インスタンスタイプ
      ImageId: ami-05576a079321f21f8 # AMI ID
      KeyName: vockey # キーペアの名前
      BlockDeviceMappings: # ブロックデバイスマッピングセクション
        - DeviceName: /dev/xvda # デバイス名
          Ebs: # EBSセクション
            VolumeSize: 10 # ボリュームサイズ
            VolumeType: gp2 # ボリュームタイプ
      Tags: # タグセクション
        - Key: Name # タグのキー
          Value: CFInstance # タグの値
      NetworkInterfaces: # ネットワークインターフェースセクション
        - SubnetId: !Ref PublicSubnet
          DeviceIndex: 0
          AssociatePublicIpAddress: true
          GroupSet:
            - !Ref CFSecurityGroup